// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-training-go/internal/action/biz"
	"api-training-go/internal/action/data"
	"api-training-go/internal/action/server"
	"api-training-go/internal/action/service"
	"api-training-go/internal/conf"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, auth *conf.Auth, client *conf.Client) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger, client)
	if err != nil {
		return nil, nil, err
	}
	actionRepo := data.NewActionRepo(dataData, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	actionUseCase := biz.NewActionUseCase(logger, actionRepo, categoryRepo, userRepo)
	actionService := service.NewActionService(actionUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, auth, actionService)
	grpcServer := server.NewGRPCServer(confServer, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
