// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-training-go/internal/category/biz"
	"api-training-go/internal/category/data"
	"api-training-go/internal/category/server"
	"api-training-go/internal/category/service"
	"api-training-go/internal/conf"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, auth *conf.Auth) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUseCase := biz.NewCategoryUseCase(logger, categoryRepo)
	categoryService := service.NewCategoryService(categoryUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, auth, categoryService)
	grpcServer := server.NewGRPCServer(confServer, logger, categoryService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
